# Generated by Django 5.1.6 on 2025-02-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_notes_alter_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='article_slug',
        ),
    ]
